export const STREAM_CONTENT = "STREAM_CONTENT";
export const SUBSCRIPTIONS_LIST = "SUBSCRIPTIONS_LIST";
export const RECOMMENDED_FEEDS = "RECOMMENDED_FEEDS";
export const STREAM_PREFERENCES = "STREAM_PREFERENCES";
export const FOLDER = "FOLDER";