export const QUERY_KEYS = {
  STREAM_CONTENT: "STREAM_CONTENT",
  SUBSCRIPTIONS_LIST: "SUBSCRIPTIONS_LIST",
  RECOMMENDED_FEEDS: "RECOMMENDED_FEEDS",
  STREAM_PREFERENCES: "STREAM_PREFERENCES",
  FOLDER: "FOLDER",
};
